# fly.toml app configuration file generated for paint-server on 2025-01-26T22:04:38+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paint-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
